### ISSUE TITLE
Close on back button press and reopen on menu item click, the search box opens and closes automatically.

### ISSUE THREAD

**Issue by anupsarode** [Quinny898/PersistentSearch#36]
I have added the search icon in the menu item in action bar. Followed the RevealActivity sample.

1 - I tap the search icon in action bar. The search box opens
2 - I tap the back button on my phone. Keyboard hides.
3 - I tap the back button again. Function closeSearch() is called.
4 - I now tap the search Icon in action bar. The search box opens and closes automatically. 

This should not be the case. Even better, just like Google Play Store app, if the user taps the back button, the keyboard should hide as well as the search box should be closed. No need of tapping two times. 

Solution to the mentioned problem is appreciated. Thanks!

Code

```
private boolean isSearchOpen;

@Override
public void onBackPressed()
{
    if(isSearchOpen)
    {
        closeSearch();
    }
    else
    {
        super.onBackPressed();
    }
}

private void openSearch()
{
    search.revealFromMenuItem(R.id.search, this);
    search.setLogoText(getResources().getString(R.string.app_name));

    search.setSearchListener(new SearchBox.SearchListener()
    {
        @Override
        public void onSearchOpened()
        {
            isSearchOpen = true;
        }

        @Override
        public void onSearchClosed()
        {
            closeSearch();
        }

        @Override
        public void onSearchTermChanged()
        {
            
        }

        @Override
        public void onSearch(String searchTerm)
        {
            
        }

        @Override
        public void onSearchCleared()
        {

        }
    });
}

private void closeSearch()
{
    search.hideCircularly(this);
    isSearchOpen = false;
}
```

**Comment by bateramos** [comment]
if you use toogleSearch() instead of hideCircularly(), it will work as intended.

**Comment by anupsarode** [comment]
I added the search.toggleSearch(); just before search.hideCircularly(this) in the closeSearch() function.

Now, I am getting a StackOverflow error. Following is the stack trace

```
07-02 15:16:48.548  15501-15501/com.mycompany.myapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.StackOverflowError
            at android.widget.TextView.sendBeforeTextChanged(TextView.java:7641)
            at android.widget.TextView.setText(TextView.java:3223)
            at android.widget.TextView.setText(TextView.java:3179)
            at android.widget.TextView.setText(TextView.java:3154)
            at com.quinny898.library.persistentsearch.SearchBox.setLogoTextInt(SearchBox.java:748)
            at com.quinny898.library.persistentsearch.SearchBox.toggleSearch(SearchBox.java:270)
            at com.mycompany.myapp.views.MainActivity.closeSearch(MainActivity.java:406)
```

**Comment by Quinny898** [comment]
Fixed this, I noticed this just before I pushed to Gradle

**Comment by eirinaios** [comment]
Hi Quinny. This bug is driving me crazy. Could you please upload your fix, as the issue remains in 1.1.0.
Thanks!

**Comment by Quinny898** [comment]
I put the fix in 1.1.0: https://vid.me/zV8Y

**Comment by sudarshansunder** [comment]
I tried @anupsarode's fix. Same thing still happens. Any suggestions?
